binance:
  apiKey: ${apiKey:NONE}
  secretKey: ${secretKey:NONE}
  symbols: ${symbols:BTCUSDT,ETHUSDT}
  longBlueCandleRate: ${longBlueCandleRate:0.004}
  leveragePerLevel: ${leveragePerLevel:1,2,3,4,5}